name: Ticket Checker

on:
  schedule:
    - cron: "*/1 * * * *"   # 每 1 分鐘執行一次（UTC 時區）
  workflow_dispatch:          # 允許手動觸發

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install requests beautifulsoup4
      - name: Run script
        env:
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
        run: python script.py
